// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
    region: 'us-east-2',
    userPoolId: 'us-east-2_XdyDueQqj',
    userPoolWebClientId: '3v7p0hnhiqhnptu97vb1su4h8q'
}

export default config;


// const awsmobile = {
//     "aws_project_region": "us-east-2"
// };


// export default awsmobile;
